2025-07-24 17:06:41.232 | INFO     | __main__:main:164 - ============================================================
2025-07-24 17:06:41.232 | INFO     | __main__:main:165 - 专门测试截图功能
2025-07-24 17:06:41.232 | INFO     | __main__:main:166 - ============================================================
2025-07-24 17:06:41.232 | INFO     | __main__:test_pymobiledevice3_screenshot:29 - === 测试 pymobiledevice3 截图 ===
2025-07-24 17:06:41.462 | INFO     | __main__:test_pymobiledevice3_screenshot:35 - 正在连接设备...
2025-07-24 17:06:41.524 | INFO     | __main__:test_pymobiledevice3_screenshot:43 - 设备信息: {} (iOS {}, {})
2025-07-24 17:06:41.525 | INFO     | __main__:test_pymobiledevice3_screenshot:46 - 正在创建截图服务...
2025-07-24 17:06:41.527 | ERROR    | __main__:test_pymobiledevice3_screenshot:71 - pymobiledevice3 截图失败: InvalidService
Traceback (most recent call last):

  File "/Users/liuweigang/sgzAss/test_screenshot_only.py", line 210, in <module>
    exit(main())
         └ <function main at 0x11881ba30>

  File "/Users/liuweigang/sgzAss/test_screenshot_only.py", line 172, in main
    success, path = test_pymobiledevice3_screenshot()
                    └ <function test_pymobiledevice3_screenshot at 0x1163d9480>

> File "/Users/liuweigang/sgzAss/test_screenshot_only.py", line 47, in test_pymobiledevice3_screenshot
    screenshot_service = ScreenshotService(lockdown=lockdown_client)
                         │                          └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
                         └ <class 'pymobiledevice3.services.screenshot.ScreenshotService'>

  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/services/screenshot.py", line 10, in __init__
    super().__init__(lockdown, self.SERVICE_NAME, is_developer_service=True)
                     │         │    └ 'com.apple.mobile.screenshotr'
                     │         └ <pymobiledevice3.services.screenshot.ScreenshotService object at 0x11ca06d40>
                     └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/services/lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
              │             │                                └ False
              │             └ 'com.apple.mobile.screenshotr'
              └ <bound method LockdownServiceProvider.start_lockdown_developer_service of <PlistUsbmuxLockdownClient ID:00008132-000A51622239...
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown_service_provider.py", line 55, in start_lockdown_developer_service
    return self.start_lockdown_service(name, include_escrow_bag=include_escrow_bag)
           │    │                      │                        └ False
           │    │                      └ 'com.apple.mobile.screenshotr'
           │    └ <function LockdownClient.start_lockdown_service at 0x11ca28550>
           └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 70, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           │  │       └ {'include_escrow_bag': False}
           │  └ (<PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>, 'com.apple.mobile.screensho...
           └ <function LockdownClient.start_lockdown_service at 0x11ca28430>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 508, in start_lockdown_service
    attr = self.get_service_connection_attributes(name, include_escrow_bag=include_escrow_bag)
           │    │                                 │                        └ False
           │    │                                 └ 'com.apple.mobile.screenshotr'
           │    └ <function LockdownClient.get_service_connection_attributes at 0x11ca283a0>
           └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 498, in get_service_connection_attributes
    response = self._request('StartService', options)
               │    │                        └ {'Service': 'com.apple.mobile.screenshotr'}
               │    └ <function LockdownClient._request at 0x11ca28940>
               └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 588, in _request
    raise exception_errors.get(error, LockdownError)(error, self.identifier)
          │                │   │      │              │      │    └ '00008132-000A51622239001C'
          │                │   │      │              │      └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
          │                │   │      │              └ 'InvalidService'
          │                │   │      └ <class 'pymobiledevice3.exceptions.LockdownError'>
          │                │   └ 'InvalidService'
          │                └ <method 'get' of 'dict' objects>
          └ {'PasswordProtected': <class 'pymobiledevice3.exceptions.PasswordRequiredError'>, 'PairingDialogResponsePending': <class 'pym...

pymobiledevice3.exceptions.InvalidServiceError: InvalidService
2025-07-24 17:06:41.531 | ERROR    | __main__:main:177 - ❌ pymobiledevice3 截图失败
2025-07-24 17:06:41.531 | INFO     | __main__:main:179 - ----------------------------------------
2025-07-24 17:06:41.531 | INFO     | __main__:test_idevicescreenshot:77 - === 测试传统 idevicescreenshot 方法 ===
2025-07-24 17:06:41.531 | INFO     | __main__:test_idevicescreenshot:80 - 检查设备连接...
2025-07-24 17:06:41.788 | INFO     | __main__:test_idevicescreenshot:90 - 检测到设备: K.T.S ipad pro M4
2025-07-24 17:06:41.789 | INFO     | __main__:test_idevicescreenshot:96 - 正在获取截图...
2025-07-24 17:06:42.036 | ERROR    | __main__:test_idevicescreenshot:103 - idevicescreenshot 失败: 
2025-07-24 17:06:42.036 | ERROR    | __main__:main:187 - ❌ idevicescreenshot 截图失败
2025-07-24 17:06:42.037 | INFO     | __main__:main:189 - ----------------------------------------
2025-07-24 17:06:42.037 | INFO     | __main__:test_libimobiledevice_screenshot:135 - === 测试 libimobiledevice 其他截图方法 ===
2025-07-24 17:06:42.037 | INFO     | __main__:test_libimobiledevice_screenshot:140 - 尝试使用 TIFF 格式...
2025-07-24 17:06:42.046 | WARNING  | __main__:test_libimobiledevice_screenshot:155 - TIFF 格式截图失败: 
2025-07-24 17:06:42.046 | ERROR    | __main__:main:197 - ❌ libimobiledevice 其他方法截图失败
2025-07-24 17:06:42.046 | INFO     | __main__:main:199 - ============================================================
2025-07-24 17:06:42.046 | INFO     | __main__:main:200 - 测试完成: 0/3 个方法成功
2025-07-24 17:06:42.047 | ERROR    | __main__:main:206 - 所有截图方法都失败了
2025-07-24 17:09:15.067 | INFO     | __main__:main:238 - ============================================================
2025-07-24 17:09:15.067 | INFO     | __main__:main:239 - 专门测试截图功能
2025-07-24 17:09:15.067 | INFO     | __main__:main:240 - ============================================================
2025-07-24 17:09:15.067 | INFO     | __main__:test_pymobiledevice3_with_tunneld:88 - === 测试 pymobiledevice3 通过 tunneld 截图 ===
2025-07-24 17:09:15.067 | INFO     | __main__:start:37 - 正在启动 pymobiledevice3 tunneld 服务...
2025-07-24 17:09:15.228 | INFO     | __main__:start:44 - tunneld 服务已在运行
2025-07-24 17:09:17.229 | INFO     | __main__:test_pymobiledevice3_with_tunneld:101 - 正在通过 tunneld 获取截图...
2025-07-24 17:09:18.466 | INFO     | __main__:test_pymobiledevice3_with_tunneld:113 - 截图获取成功，耗时: 1.23秒
2025-07-24 17:09:18.467 | INFO     | __main__:test_pymobiledevice3_with_tunneld:114 - 截图已保存到: pymobiledevice3_tunneld_1753348157.png
2025-07-24 17:09:18.467 | INFO     | __main__:test_pymobiledevice3_with_tunneld:115 - 截图尺寸: 2752x2064
2025-07-24 17:09:18.467 | INFO     | __main__:test_pymobiledevice3_with_tunneld:116 - 截图格式: RGB
2025-07-24 17:09:18.467 | INFO     | __main__:main:251 - ✅ pymobiledevice3 + tunneld 截图成功: pymobiledevice3_tunneld_1753348157.png
2025-07-24 17:09:18.467 | INFO     | __main__:main:255 - ----------------------------------------
2025-07-24 17:09:18.467 | INFO     | __main__:test_pymobiledevice3_direct:133 - === 测试 pymobiledevice3 直接截图 ===
2025-07-24 17:09:18.676 | INFO     | __main__:test_pymobiledevice3_direct:139 - 正在连接设备...
2025-07-24 17:09:18.744 | INFO     | __main__:test_pymobiledevice3_direct:147 - 设备信息: {} (iOS {}, {})
2025-07-24 17:09:18.744 | INFO     | __main__:test_pymobiledevice3_direct:150 - 正在创建截图服务...
2025-07-24 17:09:18.746 | ERROR    | __main__:test_pymobiledevice3_direct:175 - pymobiledevice3 直接截图失败: InvalidService
Traceback (most recent call last):

  File "/Users/liuweigang/sgzAss/test_screenshot_only.py", line 289, in <module>
    exit(main())
         └ <function main at 0x10a34fd00>

  File "/Users/liuweigang/sgzAss/test_screenshot_only.py", line 258, in main
    success, path = test_pymobiledevice3_direct()
    │               └ <function test_pymobiledevice3_direct at 0x10a34fbe0>
    └ True

> File "/Users/liuweigang/sgzAss/test_screenshot_only.py", line 151, in test_pymobiledevice3_direct
    screenshot_service = ScreenshotService(lockdown=lockdown_client)
                         │                          └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
                         └ <class 'pymobiledevice3.services.screenshot.ScreenshotService'>

  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/services/screenshot.py", line 10, in __init__
    super().__init__(lockdown, self.SERVICE_NAME, is_developer_service=True)
                     │         │    └ 'com.apple.mobile.screenshotr'
                     │         └ <pymobiledevice3.services.screenshot.ScreenshotService object at 0x11a4e4190>
                     └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/services/lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
              │             │                                └ False
              │             └ 'com.apple.mobile.screenshotr'
              └ <bound method LockdownServiceProvider.start_lockdown_developer_service of <PlistUsbmuxLockdownClient ID:00008132-000A51622239...
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown_service_provider.py", line 55, in start_lockdown_developer_service
    return self.start_lockdown_service(name, include_escrow_bag=include_escrow_bag)
           │    │                      │                        └ False
           │    │                      └ 'com.apple.mobile.screenshotr'
           │    └ <function LockdownClient.start_lockdown_service at 0x11a4b8f70>
           └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 70, in _inner_reconnect_on_remote_close
    return f(*args, **kwargs)
           │  │       └ {'include_escrow_bag': False}
           │  └ (<PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>, 'com.apple.mobile.screensho...
           └ <function LockdownClient.start_lockdown_service at 0x11a4b8e50>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 508, in start_lockdown_service
    attr = self.get_service_connection_attributes(name, include_escrow_bag=include_escrow_bag)
           │    │                                 │                        └ False
           │    │                                 └ 'com.apple.mobile.screenshotr'
           │    └ <function LockdownClient.get_service_connection_attributes at 0x11a4b8dc0>
           └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 498, in get_service_connection_attributes
    response = self._request('StartService', options)
               │    │                        └ {'Service': 'com.apple.mobile.screenshotr'}
               │    └ <function LockdownClient._request at 0x11a4b9360>
               └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
  File "/Users/liuweigang/anaconda3/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 588, in _request
    raise exception_errors.get(error, LockdownError)(error, self.identifier)
          │                │   │      │              │      │    └ '00008132-000A51622239001C'
          │                │   │      │              │      └ <PlistUsbmuxLockdownClient ID:00008132-000A51622239001C VERSION:26.0 TYPE:iPad16,5 PAIRED:True>
          │                │   │      │              └ 'InvalidService'
          │                │   │      └ <class 'pymobiledevice3.exceptions.LockdownError'>
          │                │   └ 'InvalidService'
          │                └ <method 'get' of 'dict' objects>
          └ {'PasswordProtected': <class 'pymobiledevice3.exceptions.PasswordRequiredError'>, 'PairingDialogResponsePending': <class 'pym...

pymobiledevice3.exceptions.InvalidServiceError: InvalidService
2025-07-24 17:09:18.750 | ERROR    | __main__:main:264 - ❌ pymobiledevice3 直接截图失败
2025-07-24 17:09:18.750 | INFO     | __main__:main:266 - ----------------------------------------
2025-07-24 17:09:18.751 | INFO     | __main__:test_idevicescreenshot:181 - === 测试传统 idevicescreenshot 方法 ===
2025-07-24 17:09:18.751 | INFO     | __main__:test_idevicescreenshot:184 - 检查设备连接...
2025-07-24 17:09:19.006 | INFO     | __main__:test_idevicescreenshot:194 - 检测到设备: K.T.S ipad pro M4
2025-07-24 17:09:19.006 | INFO     | __main__:test_idevicescreenshot:200 - 正在获取截图...
2025-07-24 17:09:19.252 | ERROR    | __main__:test_idevicescreenshot:207 - idevicescreenshot 失败: 
2025-07-24 17:09:19.253 | ERROR    | __main__:main:275 - ❌ idevicescreenshot 截图失败
2025-07-24 17:09:19.253 | INFO     | __main__:main:277 - ============================================================
2025-07-24 17:09:19.253 | INFO     | __main__:main:278 - 测试完成: 1/3 个方法成功
2025-07-24 17:09:19.253 | INFO     | __main__:main:281 - 可用的截图方法: pymobiledevice3 + tunneld
2025-07-24 17:09:19.253 | INFO     | __main__:main:282 - 建议优先使用 pymobiledevice3 + tunneld 方法
